/* Generated by fw-automation-agent. Do not edit by hand.
 * Target: ATmega328P (AVR)
 */
#ifndef CONFIG_H
#define CONFIG_H

/* Identity, so a device on a bench can be matched to the build that produced
 * it -- a prerequisite for knowing whether a given unit carries a fix. */
#define FIRMWARE_VERSION "0.1.0"
#define BUILD_ID         "765e0d32"

#define MCU_NAME        "ATmega328P"
#define MCU_FAMILY      "AVR"
#define F_CPU           16000000UL
#define MCU_FLASH_KB    32
#define MCU_RAM_KB      2
#define SUPPLY_VOLTAGE_MV 5000

#define SENSOR_COUNT    3
#define LOOP_PERIOD_MS  2000
/* Gap between consecutive sensor reads: the HC-SR04 needs its previous
 * burst to decay before the next trigger. */
#define SENSOR_SETTLE_MS 60

/* USART0: 9600 baud requested, 9615 actual (0.16 % error). */
#define UART_BAUD       9600
#define UART_UBRR       103

/* Watchdog: 8000 ms, against a worst-case loop of about
 * 3320 ms. */
#define WATCHDOG_TIMEOUT_MS 8000


/* DHT22 - temperature_humidity over GPIO */
#define DHT22_SIGNAL_PORT   PORTD
#define DHT22_SIGNAL_DDR    DDRD
#define DHT22_SIGNAL_PIN    PIND
#define DHT22_SIGNAL_BIT    2
#define DHT22_REQUIRED 1

/* HC-SR04 - ultrasonic_distance over GPIO */
#define HC_SR04_TRIGGER_PORT   PORTB
#define HC_SR04_TRIGGER_DDR    DDRB
#define HC_SR04_TRIGGER_PIN    PINB
#define HC_SR04_TRIGGER_BIT    1
#define HC_SR04_ECHO_PORT   PORTB
#define HC_SR04_ECHO_DDR    DDRB
#define HC_SR04_ECHO_PIN    PINB
#define HC_SR04_ECHO_BIT    2
#define HC_SR04_REQUIRED 1

/* LDR - light_level over ADC */
#define LDR_SIGNAL_PORT   PORTC
#define LDR_SIGNAL_DDR    DDRC
#define LDR_SIGNAL_PIN    PINC
#define LDR_SIGNAL_BIT    0
#define LDR_SIGNAL_ADC_CHANNEL 0
#define LDR_REQUIRED 0

#endif /* CONFIG_H */
