/* Generated by fw-automation-agent. Do not edit by hand.
 *
 * DHT22 single-wire protocol:
 *   1. Host pulls the line low for >= 1 ms, then releases it.
 *   2. Sensor answers with 80 us low + 80 us high.
 *   3. 40 data bits follow. Each bit is 50 us low, then high for
 *      ~26 us (a 0) or ~70 us (a 1) -- the high time carries the value.
 *   4. Bytes are RH-high, RH-low, T-high, T-low, checksum; the checksum is
 *      the low 8 bits of the sum of the first four.
 *
 * Bit timing is measured by busy-waiting in ~1 us steps with interrupts off,
 * so the driver must not be called from an ISR.
 */
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <stdint.h>

#include "config.h"
#include "dht22.h"

#define DHT22_LINE_HIGH() \
    ((DHT22_SIGNAL_PIN & (uint8_t)(1 << DHT22_SIGNAL_BIT)) != 0)

/* A 0 bit holds the line high ~26 us and a 1 bit ~70 us; split the difference. */
#define DHT22_BIT_THRESHOLD_US 45
#define DHT22_PHASE_TIMEOUT_US 200

static void dht22_drive_low(void)
{
    DHT22_SIGNAL_DDR |= (uint8_t)(1 << DHT22_SIGNAL_BIT);
    DHT22_SIGNAL_PORT &= (uint8_t)~(1 << DHT22_SIGNAL_BIT);
}

static void dht22_release(void)
{
    DHT22_SIGNAL_DDR &= (uint8_t)~(1 << DHT22_SIGNAL_BIT);
    DHT22_SIGNAL_PORT |= (uint8_t)(1 << DHT22_SIGNAL_BIT);
}

/* Wait while the line stays at `level`. Returns the elapsed microseconds, or
 * 0xFF if the phase never ended. */
static uint8_t dht22_wait_while(uint8_t level)
{
    uint8_t elapsed = 0;

    while (DHT22_LINE_HIGH() == level) {
        if (elapsed >= DHT22_PHASE_TIMEOUT_US) {
            return 0xFF;
        }
        _delay_us(1);
        elapsed++;
    }

    return elapsed;
}

void dht22_init(void)
{
    dht22_release();
}

sensor_status_t dht22_read_all(int16_t *out_temp_dc, uint16_t *out_rh_dpm)
{
    uint8_t bytes[5] = {0, 0, 0, 0, 0};
    uint8_t i;
    uint8_t bit;
    uint8_t high_us;

    /* Start pulse: hold low well past the 1 ms minimum, then let the pull-up win. */
    dht22_drive_low();
    _delay_ms(2);
    dht22_release();

    cli();

    /* Sensor acknowledges: it pulls the line low, then high, ~80 us each. */
    if (dht22_wait_while(1) == 0xFF) { sei(); return SENSOR_ERR_TIMEOUT; }
    if (dht22_wait_while(0) == 0xFF) { sei(); return SENSOR_ERR_TIMEOUT; }
    if (dht22_wait_while(1) == 0xFF) { sei(); return SENSOR_ERR_TIMEOUT; }

    for (i = 0; i < 40; i++) {
        /* Each bit opens with ~50 us low. */
        if (dht22_wait_while(0) == 0xFF) { sei(); return SENSOR_ERR_TIMEOUT; }

        high_us = dht22_wait_while(1);
        if (high_us == 0xFF) { sei(); return SENSOR_ERR_TIMEOUT; }

        bit = (high_us > DHT22_BIT_THRESHOLD_US) ? 1 : 0;
        bytes[i >> 3] = (uint8_t)((bytes[i >> 3] << 1) | bit);
    }

    sei();

    return dht22_decode(bytes, out_temp_dc, out_rh_dpm);
}

sensor_status_t dht22_decode(const uint8_t bytes[5],
                                                   int16_t *out_temp_dc,
                                                   uint16_t *out_rh_dpm)
{
    uint8_t checksum;
    uint16_t raw_rh;
    uint16_t raw_t;

    if (bytes == 0) {
        return SENSOR_ERR_ARG;
    }

    checksum = (uint8_t)(bytes[0] + bytes[1] + bytes[2] + bytes[3]);
    if (checksum != bytes[4]) {
        return SENSOR_ERR_CHECKSUM;
    }

    raw_rh = (uint16_t)(((uint16_t)bytes[0] << 8) | bytes[1]);
    raw_t = (uint16_t)(((uint16_t)bytes[2] << 8) | bytes[3]);

    if (out_rh_dpm != 0) {
        *out_rh_dpm = raw_rh;
    }

    if (out_temp_dc != 0) {
        /* Bit 15 is a sign flag, not two's complement. */
        if (raw_t & 0x8000u) {
            *out_temp_dc = (int16_t)-(int16_t)(raw_t & 0x7FFFu);
        } else {
            *out_temp_dc = (int16_t)raw_t;
        }
    }

    return SENSOR_OK;
}

sensor_status_t dht22_read(uint16_t *out_value)
{
    if (out_value == 0) {
        return SENSOR_ERR_ARG;
    }
    return dht22_read_all(0, out_value);
}
