/* Generated by fw-automation-agent. Do not edit by hand.
 * DHT22 / AM2302 temperature and humidity sensor, single-wire protocol.
 */
#ifndef DHT22_H
#define DHT22_H

#include <stdint.h>
#include "sensor.h"

/* Idle the bus high; call once at startup. */
void dht22_init(void);

/* Read both channels.
 *   out_temp_dc  : temperature in tenths of a degree Celsius (-400..800)
 *   out_rh_dpm   : relative humidity in tenths of a percent (0..1000)
 * Either pointer may be NULL if that channel is not wanted.
 *
 * The sensor needs ~2 s between reads; polling faster returns stale values.
 */
sensor_status_t dht22_read_all(int16_t *out_temp_dc, uint16_t *out_rh_dpm);

/* Uniform single-value entry point used by the main loop: humidity in 0.1 %. */
sensor_status_t dht22_read(uint16_t *out_value);

/* Decode a captured 5-byte frame. Split out from the timing-critical read so
 * the arithmetic can be exercised without hardware -- see services/test_service.py.
 */
sensor_status_t dht22_decode(const uint8_t bytes[5],
                                                   int16_t *out_temp_dc,
                                                   uint16_t *out_rh_dpm);

#endif /* DHT22_H */
