/* Generated by fw-automation-agent. Do not edit by hand.
 *
 * HC-SR04 protocol:
 *   1. Host raises TRIGGER for 10 us.
 *   2. Sensor emits an 8-cycle 40 kHz burst and raises ECHO.
 *   3. ECHO stays high for the round-trip flight time; if nothing returns it
 *      falls after ~38 ms.
 *
 * The echo width is measured with Timer1 rather than a delay loop, so the
 * reading does not drift with compiler output. NOTE: this driver owns Timer1
 * -- do not also use it for PWM or a system tick.
 *
 * At 16 MHz with the /64 prescaler one tick is 4 us. Sound covers 0.343 mm/us
 * and the pulse spans there and back, so distance_mm = ticks * 4 * 0.343 / 2,
 * i.e. ticks * 686 / 1000.
 */
#include <avr/io.h>
#include <util/delay.h>
#include <stdint.h>

#include "config.h"
#include "hc_sr04.h"

#define HC_SR04_ECHO_HIGH() \
    ((HC_SR04_ECHO_PIN & (uint8_t)(1 << HC_SR04_ECHO_BIT)) != 0)

/* Timer1, prescaler 64. Valid only at F_CPU = 16 MHz. */
#if F_CPU != 16000000UL
#error "hc_sr04 driver assumes F_CPU == 16000000UL"
#endif
#define HC_SR04_TICK_NS 4000UL

/* ~120 ms: comfortably past the sensor's own ~38 ms no-echo timeout. */
#define HC_SR04_TIMEOUT_TICKS 30000U

/* Datasheet range ceiling; readings beyond this are not trustworthy. */
#define HC_SR04_MAX_DISTANCE_MM 4000U

static void hc_sr04_timer_start(void)
{
    TCCR1A = 0;
    TCNT1 = 0;
    TCCR1B = (uint8_t)((1 << CS11) | (1 << CS10)); /* prescaler 64 */
}

static void hc_sr04_timer_stop(void)
{
    TCCR1B = 0;
}

void hc_sr04_init(void)
{
    HC_SR04_TRIGGER_DDR |= (uint8_t)(1 << HC_SR04_TRIGGER_BIT);
    HC_SR04_TRIGGER_PORT &= (uint8_t)~(1 << HC_SR04_TRIGGER_BIT);

    HC_SR04_ECHO_DDR &= (uint8_t)~(1 << HC_SR04_ECHO_BIT);
    HC_SR04_ECHO_PORT &= (uint8_t)~(1 << HC_SR04_ECHO_BIT);
}

sensor_status_t hc_sr04_read_mm(uint16_t *out_distance_mm)
{
    uint16_t ticks;
    uint16_t distance_mm;

    if (out_distance_mm == 0) {
        return SENSOR_ERR_ARG;
    }

    /* 10 us trigger pulse, from a settled low. */
    HC_SR04_TRIGGER_PORT &= (uint8_t)~(1 << HC_SR04_TRIGGER_BIT);
    _delay_us(2);
    HC_SR04_TRIGGER_PORT |= (uint8_t)(1 << HC_SR04_TRIGGER_BIT);
    _delay_us(10);
    HC_SR04_TRIGGER_PORT &= (uint8_t)~(1 << HC_SR04_TRIGGER_BIT);

    /* Wait for the burst to start. */
    hc_sr04_timer_start();
    while (!HC_SR04_ECHO_HIGH()) {
        if (TCNT1 > HC_SR04_TIMEOUT_TICKS) {
            hc_sr04_timer_stop();
            return SENSOR_ERR_TIMEOUT;
        }
    }

    /* Time the echo. */
    TCNT1 = 0;
    while (HC_SR04_ECHO_HIGH()) {
        if (TCNT1 > HC_SR04_TIMEOUT_TICKS) {
            hc_sr04_timer_stop();
            return SENSOR_ERR_TIMEOUT;
        }
    }
    ticks = TCNT1;
    hc_sr04_timer_stop();

    distance_mm = hc_sr04_ticks_to_mm(ticks);

    if (distance_mm > HC_SR04_MAX_DISTANCE_MM) {
        return SENSOR_ERR_OUT_OF_RANGE;
    }

    *out_distance_mm = (uint16_t)distance_mm;
    return SENSOR_OK;
}

uint16_t hc_sr04_ticks_to_mm(uint16_t ticks)
{
    /* The 32-bit intermediate matters: ticks * 686 overflows 16 bits above
     * 95 ticks, which is only 65 mm. */
    return (uint16_t)(((uint32_t)ticks * 686UL) / 1000UL);
}

sensor_status_t hc_sr04_read(uint16_t *out_value)
{
    return hc_sr04_read_mm(out_value);
}
