/* Generated by fw-automation-agent. Do not edit by hand.
 * HC-SR04 ultrasonic distance sensor.
 */
#ifndef HC_SR04_H
#define HC_SR04_H

#include <stdint.h>
#include "sensor.h"

/* Trigger as output (idle low), echo as input; call once at startup. */
void hc_sr04_init(void);

/* Measure distance in millimetres.
 *
 * Returns SENSOR_ERR_TIMEOUT if no echo came back, and
 * SENSOR_ERR_OUT_OF_RANGE if the echo implies a distance past the sensor's
 * usable ~4 m ceiling. Leave >= 60 ms between calls so the previous burst
 * has decayed.
 */
sensor_status_t hc_sr04_read_mm(uint16_t *out_distance_mm);

/* Uniform single-value entry point used by the main loop. */
sensor_status_t hc_sr04_read(uint16_t *out_value);

/* Convert a Timer1 tick count into millimetres. Split out from the timed read
 * so the arithmetic can be exercised without hardware.
 */
uint16_t hc_sr04_ticks_to_mm(uint16_t ticks);

#endif /* HC_SR04_H */
