/* Generated by fw-automation-agent. Do not edit by hand.
 * Analog input on LDR.
 */
#ifndef LDR_H
#define LDR_H

#include <stdint.h>
#include "sensor.h"

/* Leave the pin as a high-impedance input and enable the ADC. */
void ldr_init(void);

/* Raw 10-bit conversion result, 0..1023. */
sensor_status_t ldr_read(uint16_t *out_value);

/* Same reading scaled to millivolts against the supply rail. */
sensor_status_t ldr_read_mv(uint16_t *out_millivolts);

#endif /* LDR_H */
