/* Generated by fw-automation-agent. Do not edit by hand.
 *
 * Single-ended ADC read on LDR. AVcc is the reference and the
 * prescaler is /128, keeping the ADC clock at 125000 Hz --
 * inside the 50-200 kHz window the ATmega328P needs for full 10-bit accuracy.
 */
#include <avr/io.h>
#include <stdint.h>

#include "config.h"
#include "ldr.h"

void ldr_init(void)
{
    LDR_SIGNAL_DDR &= (uint8_t)~(1 << LDR_SIGNAL_BIT);
    LDR_SIGNAL_PORT &= (uint8_t)~(1 << LDR_SIGNAL_BIT);

    ADMUX = (uint8_t)(1 << REFS0);
    ADCSRA = (uint8_t)((1 << ADEN) | (1 << ADPS2) | (1 << ADPS1) | (1 << ADPS0));
}

sensor_status_t ldr_read(uint16_t *out_value)
{
    if (out_value == 0) {
        return SENSOR_ERR_ARG;
    }

    ADMUX = (uint8_t)((ADMUX & 0xF0u) | (LDR_SIGNAL_ADC_CHANNEL & 0x0Fu));
    ADCSRA |= (uint8_t)(1 << ADSC);
    while (ADCSRA & (uint8_t)(1 << ADSC)) {
        /* conversion in progress */
    }

    *out_value = ADC;
    return SENSOR_OK;
}

sensor_status_t ldr_read_mv(uint16_t *out_millivolts)
{
    uint16_t raw;
    sensor_status_t status;

    if (out_millivolts == 0) {
        return SENSOR_ERR_ARG;
    }

    status = ldr_read(&raw);
    if (status != SENSOR_OK) {
        return status;
    }

    *out_millivolts = (uint16_t)(((uint32_t)raw * SUPPLY_VOLTAGE_MV) / 1023UL);
    return SENSOR_OK;
}
