/* Generated by fw-automation-agent. Do not edit by hand.
 * Target: ATmega328P @ 16000000 Hz
 *
 * Reads every sensor once per loop and reports over UART at 9600 baud.
 * A failed read prints an explicit error code -- no placeholder value is ever
 * emitted in place of a real measurement.
 *
 * Output lines look like:
 *   DHT22 T=23.5C RH=45.2%
 *   HC-SR04 d=1245mm
 *   LDR adc=512 (1234mV)
 *   <name> ERR=<code>
 */
#include <avr/io.h>
#include <util/delay.h>
#include <stdint.h>

#include "config.h"
#include "sensor.h"
#include "uart.h"
#include "watchdog.h"
#include "dht22.h"
#include "hc_sr04.h"
#include "ldr.h"

static void report_error(const char *name, sensor_status_t status)
{
    uart_write_string(name);
    uart_write_string(" ERR=");
    uart_write_u16((uint16_t)status);
    uart_write_string("\r\n");
}

static void board_init(void)
{
    uart_init();
    watchdog_init();
    dht22_init();
    hc_sr04_init();
    ldr_init();
}

int main(void)
{
    sensor_status_t status = SENSOR_OK;
    int16_t temp_dc = 0;
    uint16_t rh_dpm = 0;
    uint16_t reading = 0;
    uint16_t millivolts = 0;

    board_init();
    uart_write_string("\r\n" MCU_NAME " " FIRMWARE_VERSION " (" BUILD_ID ") up\r\n");
    if (watchdog_caused_last_reset()) {
        /* Surfaced rather than swallowed: from the outside, a device that is
         * quietly rebooting in a loop looks the same as one that is working. */
        uart_write_string("WARN previous reset was the watchdog\r\n");
    }

    for (;;) {
        watchdog_kick();
        status = dht22_read_all(&temp_dc, &rh_dpm);
        if (status == SENSOR_OK) {
            uart_write_string("DHT22 T=");
            uart_write_tenths(temp_dc);
            uart_write_string("C RH=");
            uart_write_tenths((int16_t)rh_dpm);
            uart_write_string("%\r\n");
        } else {
            report_error("DHT22", status);
        }
        _delay_ms(SENSOR_SETTLE_MS);
        status = hc_sr04_read_mm(&reading);
        if (status == SENSOR_OK) {
            uart_write_string("HC-SR04 d=");
            uart_write_u16(reading);
            uart_write_string("mm\r\n");
        } else {
            report_error("HC-SR04", status);
        }
        _delay_ms(SENSOR_SETTLE_MS);
        status = ldr_read(&reading);
        if (status == SENSOR_OK) {
            uart_write_string("LDR adc=");
            uart_write_u16(reading);
            if (ldr_read_mv(&millivolts) == SENSOR_OK) {
                uart_write_string(" (");
                uart_write_u16(millivolts);
                uart_write_string("mV)");
            }
            uart_write_string("\r\n");
        } else {
            report_error("LDR", status);
        }
        watchdog_kick();
        _delay_ms(LOOP_PERIOD_MS);
    }

    return 0;
}
