/* Generated by fw-automation-agent. Do not edit by hand.
 * Shared sensor result type.
 */
#ifndef SENSOR_H
#define SENSOR_H

#include <stdint.h>

typedef enum {
    SENSOR_OK = 0,
    SENSOR_ERR_TIMEOUT = 1,
    SENSOR_ERR_CHECKSUM = 2,
    SENSOR_ERR_ARG = 3,
    SENSOR_ERR_OUT_OF_RANGE = 4
} sensor_status_t;

#endif /* SENSOR_H */
