/* Generated by fw-automation-agent. Do not edit by hand.
 * Blocking UART output on USART0 at 9600 baud, 8N1.
 * Transmit only -- there is no receive path.
 */
#ifndef UART_H
#define UART_H

#include <stdint.h>

void uart_init(void);

void uart_write_char(char c);
void uart_write_string(const char *s);

/* Decimal, no leading zeros. Avoids pulling in stdio, which would cost more
 * flash than the whole rest of this firmware. */
void uart_write_u16(uint16_t value);
void uart_write_i16(int16_t value);

/* Print `value` scaled by 10 as a fixed-point number with one decimal --
 * the sensors report tenths, so 235 prints as "23.5". */
void uart_write_tenths(int16_t tenths);

#endif /* UART_H */
