/* Generated by fw-automation-agent. Do not edit by hand.
 *
 * USART0 at 9600 baud, 8 data bits, no parity, 1 stop bit.
 *
 * Which USART this is depends on the part: the ATmega328P has USART0, the
 * ATmega32U4 only has USART1, and the ATtiny2313's registers carry no index
 * at all. The suffix comes from the part's own avr-libc header, so the right
 * registers are used without a per-part template.
 *
 * UBRR = F_CPU / (16 * baud) - 1 = 103 at 16000000 Hz,
 * for an actual rate of 9615 baud (0.16 % error --
 * receivers tolerate about 2 %).
 */
#include <avr/io.h>
#include <stdint.h>

#include "config.h"
#include "uart.h"

void uart_init(void)
{
    UBRR0H = (uint8_t)(UART_UBRR >> 8);
    UBRR0L = (uint8_t)(UART_UBRR & 0xFFu);

    /* Transmit only: the receiver is deliberately left disabled, so the
     * firmware exposes no serial input to accept commands on. */
    UCSR0B = (uint8_t)(1 << TXEN0);
    UCSR0C = (uint8_t)((1 << UCSZ01) | (1 << UCSZ00)); /* 8N1 */
}

void uart_write_char(char c)
{
    while (!(UCSR0A & (uint8_t)(1 << UDRE0))) {
        /* transmit buffer busy */
    }
    UDR0 = (uint8_t)c;
}

void uart_write_string(const char *s)
{
    if (s == 0) {
        return;
    }
    while (*s != '\0') {
        uart_write_char(*s++);
    }
}

void uart_write_u16(uint16_t value)
{
    char digits[5];
    uint8_t count = 0;

    if (value == 0) {
        uart_write_char('0');
        return;
    }

    while (value > 0 && count < 5) {
        digits[count++] = (char)('0' + (value % 10u));
        value /= 10u;
    }

    while (count > 0) {
        uart_write_char(digits[--count]);
    }
}

void uart_write_i16(int16_t value)
{
    if (value < 0) {
        uart_write_char('-');
        /* Negate as unsigned so INT16_MIN doesn't overflow. */
        uart_write_u16((uint16_t)(-(int32_t)value));
    } else {
        uart_write_u16((uint16_t)value);
    }
}

void uart_write_tenths(int16_t tenths)
{
    uint16_t magnitude;

    if (tenths < 0) {
        uart_write_char('-');
        magnitude = (uint16_t)(-(int32_t)tenths);
    } else {
        magnitude = (uint16_t)tenths;
    }

    uart_write_u16((uint16_t)(magnitude / 10u));
    uart_write_char('.');
    uart_write_char((char)('0' + (magnitude % 10u)));
}
