/* Generated by fw-automation-agent. Do not edit by hand.
 *
 * The watchdog exists so a device that stops making progress -- a sensor that
 * never releases the bus, a loop that wedges -- recovers itself instead of
 * going quiet until someone notices.
 *
 * There is a trap in doing this on AVR, and getting it wrong turns a recovery
 * mechanism into a brick: after a watchdog reset the WDT stays enabled with
 * its *shortest* timeout (about 16 ms). If the program does not disable it
 * before reaching code that takes longer than that, the device resets again,
 * and again, forever. So the disable runs from .init3, before main() and
 * before any initialisation that could outlast 16 ms.
 *
 * MCUSR is saved before being cleared, because clearing it is also required
 * (leaving WDRF set makes WDE impossible to clear) and it is the only record
 * of why the device restarted.
 */
#include <avr/io.h>
#include <avr/wdt.h>
#include <stdint.h>

#include "config.h"
#include "watchdog.h"

/* .noinit: survives the reset that the value is describing. */
static uint8_t reset_flags __attribute__((section(".noinit")));

void watchdog_early_disable(void) __attribute__((naked, used, section(".init3")));

void watchdog_early_disable(void)
{
    reset_flags = MCUSR;
    MCUSR = 0;
    wdt_disable();
}

void watchdog_init(void)
{
    wdt_enable(WDTO_8S);
}

void watchdog_kick(void)
{
    wdt_reset();
}

uint8_t watchdog_caused_last_reset(void)
{
    return (uint8_t)((reset_flags & (uint8_t)(1 << WDRF)) != 0);
}
